USE DATABASE SANDBOX
;

USE SCHEMA TIM_WILSON
;

CREATE TABLE CONTROL_LOAD_DATETIME (
    LOAD_DATETIME TIMESTAMP_NTZ
)
;

CREATE FUNCTION get_load_datetime() RETURNS TIMESTAMP_NTZ as 'SELECT LOAD_DATETIME FROM CONTROL_LOAD_DATETIME'
;

DROP FUNCTION get_load_datetime()
;

INSERT INTO CONTROL_LOAD_DATETIME
(
    LOAD_DATETIME
)
VALUES
(
    '2023-02-01' :: TIMESTAMP_NTZ
)
;

TRUNCATE TABLE CONTROL_LOAD_DATETIME
;

INSERT INTO CONTROL_LOAD_DATETIME
(
    LOAD_DATETIME
)
VALUES
(
    '2023-02-02' :: TIMESTAMP_NTZ
)
;


SELECT * FROM SANDBOX.TIM_WILSON.CONTROL_LOAD_DATETIME;

SELECT GET_LOAD_DATETIME()
;

DROP TABLE INTEGRA_DATAVAULT_DEV.TW_RAW_VAULT.HUB_ORGANIZATION
;


DROP SCHEMA TW;
DROP SCHEMA TW_BUSINESS_VAULT;
DROP SCHEMA TW_PRIMED_STAGE;
DROP SCHEMA TW_RAW_STAGE;
DROP SCHEMA TW_RAW_VAULT;
DROP SCHEMA TW_RECON_MARTS;
DROP SCHEMA TW_SEEDS;


SELECT t.*, c.HCPC_CATG_ID
FROM INTEGRA_FIVETRAN.PUBLIC.HCPC_CATEGORY_TYPES AS t
LEFT OUTER JOIN INTEGRA_FIVETRAN.PUBLIC.HCPC_CATEGORIES AS c
ON t.HCPC_CATG_TYPE_ID = c.HCPC_CATG_TYPE_ID
;

SELECT *
FROM INTEGRA_FIVETRAN.PUBLIC.HCPC_CATEGORY_CODES
;


SELECT *
FROM INTEGRA_DATAVAULT_DEV.TW_RECON_MARTS.RECONCILIATION_LNK_HCPC_HIERARCHY
;

SELECT *
FROM INTEGRA_DATAVAULT_DEV.TW_BUSINESS_VAULT.PIT_ORDERS
;