SELECT *
    ,RANK() OVER (PARTITION BY PK ORDER BY HASHDIFF) AS rank_hashdiff
    ,RANK() OVER (PARTITION BY PK ORDER BY HASHDIFF, CDK) AS rank_hashdiff_cdk
    ,DENSE_RANK() OVER (PARTITION BY PK ORDER BY HASHDIFF) AS dense_rank_hashdiff
    ,DENSE_RANK() OVER (PARTITION BY PK ORDER BY HASHDIFF, CDK) AS dense_rank_hashdiff_cdk
FROM
(
SELECT '1' AS PK, '10' AS CDK, 'AAA' AS HASHDIFF, 'aaa' AS PAYLOAD
UNION ALL
SELECT '1' AS PK, '11' AS CDK, 'AAA' AS HASHDIFF, 'aaa' AS PAYLOAD
UNION ALL
SELECT '1' AS PK, '12' AS CDK, 'AAA' AS HASHDIFF, 'aaa' AS PAYLOAD
UNION ALL
SELECT '1' AS PK, '13' AS CDK, 'BBB' AS HASHDIFF, 'bbb' AS PAYLOAD
) AS testdata
;
