USE DATABASE SNOWFLAKE;

--  Create DEVELOPER role and issue grants

USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS DEVELOPER;

GRANT ROLE DEVELOPER TO ROLE SYSADMIN;


--  Create INGEST_DEV database, for landing data. Schemas named after the source should be created here.

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS INGEST_DEV;

GRANT USAGE ON DATABASE INGEST_DEV TO ROLE DEVELOPER;

-- GRANT READ-ONLY ON INGEST_DEV to DEVELOPERS

USE ROLE SECURITYADMIN;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE INGEST_DEV TO ROLE DEVELOPER;

GRANT SELECT ON FUTURE TABLES IN DATABASE INGEST_DEV TO ROLE DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE INGEST_DEV TO ROLE DEVELOPER;

--  Create DEVELOPMENT database and schemas

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS DEVELOPMENT;

USE DATABASE DEVELOPMENT;

CREATE SCHEMA IF NOT EXISTS DEVELOPMENT.STAGING;

CREATE SCHEMA IF NOT EXISTS DEVELOPMENT.RAW_VAULT;

CREATE SCHEMA IF NOT EXISTS DEVELOPMENT.BUSINESS_VAULT;

CREATE SCHEMA IF NOT EXISTS DEVELOPMENT.DATA_PRODUCTS;


-- GRANTS TO DEVELOPER ROLE FOR DEVELOPMENT DB

USE ROLE SYSADMIN;

GRANT USAGE ON DATABASE DEVELOPMENT TO ROLE DEVELOPER;

GRANT USAGE, CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE DEVELOPMENT TO ROLE DEVELOPER;

-- Grant FUTURE tables and views for each schema

USE ROLE SECURITYADMIN;

GRANT SELECT ON FUTURE TABLES IN SCHEMA DEVELOPMENT.STAGING TO ROLE DEVELOPER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEVELOPMENT.STAGING TO ROLE DEVELOPER;

GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA DEVELOPMENT.RAW_VAULT TO ROLE DEVELOPER;
GRANT SELECT, INSERT ON FUTURE VIEWS IN SCHEMA DEVELOPMENT.RAW_VAULT TO ROLE DEVELOPER;

GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA DEVELOPMENT.BUSINESS_VAULT TO ROLE DEVELOPER;
GRANT SELECT, INSERT ON FUTURE VIEWS IN SCHEMA DEVELOPMENT.BUSINESS_VAULT TO ROLE DEVELOPER;

GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA DEVELOPMENT.DATA_PRODUCTS TO ROLE DEVELOPER;
GRANT SELECT, INSERT ON FUTURE VIEWS IN SCHEMA DEVELOPMENT.DATA_PRODUCTS TO ROLE DEVELOPER;