SET USER_NAME = 'EXAMPLE_USER';

USE DATABASE SNOWFLAKE;
USE ROLE USERADMIN;

ALTER USER IDENTIFIER($USER_NAME) SET DEFAULT_ROLE = $USER_NAME;
ALTER USER IDENTIFIER($USER_NAME) SET DEFAULT_NAMESPACE = $USER_NAME;
ALTER USER IDENTIFIER($USER_NAME) SET DEFAULT_WAREHOUSE = SANDBOX_XS;