DROP SCHEMA BMC_ZUORA_STAGING
;

DROP SCHEMA BMC_ZUORA_PRIMED_STAGING
;

DROP SCHEMA BMC_ZUORA_RAW_VAULT
;

DROP SCHEMA STAGING
;

DROP SCHEMA VAULT
;



create or replace schema BMC_ZUORA_STAGING;

create or replace view STG_ZUORA_PRODUCT(
	ALLOWFEATURECHANGES,
	UPDATEDBYID,
	UPDATEDDATE,
	CREATEDDATE,
	DESCRIPTION,
	EFFECTIVEENDDATE,
	CATEGORY,
	CREATEDBYID,
	DELETED,
	EFFECTIVESTARTDATE,
	ID,
	NAME,
	SKU
) as (
    SELECT *
FROM DBTVAULT_DEV.BMC_ZUORA.PRODUCT
  );
create or replace view STG_ZUORA_PRODUCTRATEPLAN(
	CREATEDBYID,
	EFFECTIVEENDDATE,
	ID,
	UPDATEDBYID,
	PRODUCTID,
	UPDATEDDATE,
	DELETED,
	DESCRIPTION,
	EFFECTIVESTARTDATE,
	CREATEDDATE,
	NAME
) as (
    SELECT *
FROM DBTVAULT_DEV.BMC_ZUORA.PRODUCTRATEPLAN
  );
create or replace view STG_ZUORA_PRODUCTRATEPLANCHARGE(
	DEFAULTQUANTITY,
	DELETED,
	MAXQUANTITY,
	OVERAGECALCULATIONOPTION,
	REVRECCODE,
	TAXMODE,
	LEGACYREVENUEREPORTING,
	UPTOPERIODSTYPE,
	ADJUSTMENTREVENUEACCOUNTINGCODEID,
	BILLINGPERIODALIGNMENT,
	BILLINGTIMING,
	PRODUCTRATEPLANID,
	CREATEDBYID,
	RECOGNIZEDREVENUEACCOUNTINGCODEID,
	TAXCODE,
	DISCOUNTCLASSID,
	UPTOPERIODS,
	CONTRACTLIABILITYACCOUNTINGCODEID,
	CONTRACTRECOGNIZEDREVENUEACCOUNTINGCODEID,
	TRIGGEREVENT,
	CONTRACTASSETACCOUNTINGCODEID,
	SMOOTHINGMODEL,
	ACCOUNTINGCODE,
	ADJUSTMENTLIABILITYACCOUNTINGCODEID,
	APPLYDISCOUNTTO,
	CHARGEMODEL,
	ID,
	INCLUDEDUNITS,
	OVERAGEUNUSEDUNITSCREDITOPTION,
	NUMBEROFPERIOD,
	RATINGGROUP,
	UOM,
	REVENUERECOGNITIONRULENAME,
	DEFERREDREVENUEACCOUNT,
	DEFERREDREVENUEACCOUNTINGCODEID,
	DISCOUNTLEVEL,
	PRICECHANGEOPTION,
	USEDISCOUNTSPECIFICACCOUNTINGCODE,
	RECOGNIZEDREVENUEACCOUNT,
	SPECIFICBILLINGPERIOD,
	USETENANTDEFAULTFORPRICECHANGE,
	BILLCYCLEDAY,
	CHARGETYPE,
	ENDDATECONDITION,
	LISTPRICEBASE,
	UNBILLEDRECEIVABLESACCOUNTINGCODEID,
	NAME,
	REVRECTRIGGERCONDITION,
	DESCRIPTION,
	UPDATEDBYID,
	ACCOUNTRECEIVABLEACCOUNTINGCODEID,
	BILLCYCLETYPE,
	CREATEDDATE,
	UPDATEDDATE,
	BILLINGPERIOD,
	MINQUANTITY,
	PRICEINCREASEPERCENTAGE,
	USAGERECORDRATINGOPTION,
	TAXABLE,
	WEEKLYBILLCYCLEDAY
) as (
    SELECT *
FROM DBTVAULT_DEV.BMC_ZUORA.PRODUCTRATEPLANCHARGE
  );
create or replace view STG_ZUORA_PRODUCTRATEPLANCHARGETIER(
	ID,
	OVERAGEPRICE,
	PRICE,
	PRICEFORMAT,
	PRODUCTRATEPLANCHARGEID,
	ACTIVE,
	INCLUDEDUNITS,
	TIER,
	CREATEDDATE,
	UPDATEDBYID,
	CREATEDBYID,
	CURRENCY,
	DISCOUNTPERCENTAGE,
	UPDATEDDATE,
	STARTINGUNIT,
	DELETED,
	DISCOUNTAMOUNT,
	ENDINGUNIT
) as (
    SELECT *
FROM DBTVAULT_DEV.BMC_ZUORA.PRODUCTRATEPLANCHARGETIER
  );
  
SELECT *
FROM DBTVAULT_DEV.BMC_ZUORA.PRODUCT
;

SELECT *
FROM DBTVAULT_DEV.BMC_ZUORA.PRODUCTRATEPLAN