DROP VIEW INTEGRA_DATAVAULT_DEV.DEV.RECONCILIATION_HUB_ORGANIZATION
;

DROP SCHEMA INTEGRA_DATAVAULT_DEV.DEV
;

DROP SCHEMA INTEGRA_DATAVAULT_DEV.JS
;

DROP TABLE INTEGRA_DATAVAULT_DEV.RAW_VAULT.DBT_METRICS_DEFAULT_CALENDAR
;

DROP VIEW INTEGRA_DATAVAULT_DEV.RAW_VAULT.RECONCILIATION_HUB_ORGANIZATION
;

DROP VIEW INTEGRA_DATAVAULT_DEV.JS.RECONCILIATION_HUB_ORGANIZATION
;

DROP SCHEMA INTEGRA_DATAVAULT_DEV.DEV
;
DROP SCHEMA INTEGRA_DATAVAULT_DEV.DEV_PRIMED_STAGE
;
DROP SCHEMA INTEGRA_DATAVAULT_DEV.DEV_RAW_STAGE
;
DROP SCHEMA INTEGRA_DATAVAULT_DEV.DEV_RAW_VAULT
;
DROP SCHEMA INTEGRA_DATAVAULT_DEV.DEV_RECON_MARTS
;
DROP SCHEMA INTEGRA_DATAVAULT_DEV.DEV_SEEDS
;

DROP TABLE INTEGRA_DATAVAULT_DEV.TW.BV_TOTAL_ORDERS
;
DROP TABLE INTEGRA_DATAVAULT_DEV.TW.BV_TOTAL_ORDERS_MART
;

DROP TABLE INTEGRA_DATAVAULT_DEV.TW_BUSINESS_VAULT.BV_TOTAL_ORDERS
;
DROP TABLE INTEGRA_DATAVAULT_DEV.TW_BUSINESS_VAULT.BV_TOTAL_ORDERS_TIME
;
DROP VIEW INTEGRA_DATAVAULT_DEV.TW_BUSINESS_VAULT.BV_TOTAL_ORDERS_MART
;


SELECT COUNT(*)
FROM INTEGRA_DATAVAULT_DEV.TW_BUSINESS_VAULT.BV_PAYER_HIERARCHY_MART
;


SELECT *
FROM INTEGRA_DATAVAULT_DEV.TW_BUSINESS_VAULT.BV_PAYER_DIMENSIONS
WHERE PAYER_PLAN_COUNT != 0
ORDER BY REPORT_MONTH DESC
;

SELECT *
FROM INTEGRA_DATAVAULT_DEV.TW_RAW_VAULT.SAT_PRISM_PAYER_LOB
WHERE ACTIVE_FROM_DT >= '2022-12-01'
ORDER BY ACTIVE_FROM_DT ASC
;

SELECT * --ACTIVE_FROM_DT, ACTIVE_TO_DT, PAYER_ACCT_NAME
FROM INTEGRA_DATAVAULT_DEV.TW_BUSINESS_VAULT.BV_PAYER_HIERARCHY_MART
WHERE ACTIVE_FROM_DT >= '2022-12-01'
ORDER BY ACTIVE_FROM_DT ASC
;

