USE DATABASE SNOWFLAKE;
SET USER_NAME = 'EXAMPLE_USER';

-- Create user's personal role

USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS IDENTIFIER($USER_NAME);

GRANT ROLE IDENTIFIER($USER_NAME) TO ROLE SYSADMIN;

-- Create User's Sandbox Database

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS IDENTIFIER($USER_NAME);

USE DATABASE IDENTIFIER($USER_NAME);

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($USER_NAME);

USE ROLE SYSADMIN;

-- Transfer ownership of Schema and DB to user

GRANT OWNERSHIP ON DATABASE IDENTIFIER($USER_NAME) TO ROLE IDENTIFIER($USER_NAME);

USE DATABASE IDENTIFIER($USER_NAME);
GRANT OWNERSHIP ON SCHEMA IDENTIFIER($USER_NAME) TO ROLE IDENTIFIER($USER_NAME);

-- Grant DEVELOPER role to user's personal role

USE ROLE USERADMIN;

GRANT ROLE DEVELOPER TO ROLE IDENTIFIER($USER_NAME);

-- Grant Warehouses
-- Warehouses must exist prior to executing this script

GRANT USAGE ON WAREHOUSE SANDBOX_XS TO ROLE IDENTIFIER($USER_NAME);
GRANT USAGE ON WAREHOUSE DEV_XS TO ROLE IDENTIFIER($USER_NAME);

-- Grant Personal role to user
-- Users must exist prior to executing this script

GRANT ROLE IDENTIFIER($USER_NAME) TO USER IDENTIFIER($USER_NAME);